// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { AccountId32Like, Result } from 'dedot/codecs';
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
} from 'dedot/contracts';
import type { InkPrimitivesLangError } from './types';

export interface ConstructorQuery<ChainApi extends GenericSubstrateApi> extends GenericConstructorQuery<ChainApi> {
  /**
   *
   * @param {string} name
   * @param {AccountId32Like} superdao
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      name: string,
      superdao: AccountId32Like,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult<ChainApi>>>
  >;
}
