// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result, AccountId32Like } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
} from 'dedot/contracts';
import type {
  InkPrimitivesLangError,
  MinidaoCommonDaoError,
  SuperdaoTraitsChainCallLike,
  SuperdaoTraitsContractCallLike,
} from './types';

export interface ContractQuery<ChainApi extends GenericSubstrateApi> extends GenericContractQuery<ChainApi> {
  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xa148a32a
   **/
  getName: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<string, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x81b2cf8b
   **/
  registerVoter: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], MinidaoCommonDaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xa4279724
   **/
  deregisterVoter: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], MinidaoCommonDaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {AccountId32Like} voter
   * @param {ContractCallOptions} options
   *
   * @selector 0xf7156a78
   **/
  hasVoter: GenericContractQueryCall<
    ChainApi,
    (
      voter: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {SuperdaoTraitsChainCallLike} call
   * @param {ContractCallOptions} options
   *
   * @selector 0x547cc8db
   **/
  createSuperdaoCrossChainProposal: GenericContractQueryCall<
    ChainApi,
    (
      call: SuperdaoTraitsChainCallLike,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], MinidaoCommonDaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {SuperdaoTraitsContractCallLike} call
   * @param {ContractCallOptions} options
   *
   * @selector 0x0071768f
   **/
  createContractCallProposal: GenericContractQueryCall<
    ChainApi,
    (
      call: SuperdaoTraitsContractCallLike,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], MinidaoCommonDaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {number} proposalId
   * @param {boolean} vote
   * @param {ContractCallOptions} options
   *
   * @selector 0x946595e4
   **/
  voteProposal: GenericContractQueryCall<
    ChainApi,
    (
      proposalId: number,
      vote: boolean,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], MinidaoCommonDaoError>, ContractCallResult<ChainApi>>>
  >;
}
