// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from 'dedot/contracts';
import type { SuperdaoTraitsChainCallLike, SuperdaoTraitsContractCallLike } from './types';

export interface ContractTx<ChainApi extends GenericSubstrateApi> extends GenericContractTx<ChainApi> {
  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x81b2cf8b
   **/
  registerVoter: GenericContractTxCall<
    ChainApi,
    (options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xa4279724
   **/
  deregisterVoter: GenericContractTxCall<
    ChainApi,
    (options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {SuperdaoTraitsChainCallLike} call
   * @param {ContractTxOptions} options
   *
   * @selector 0x547cc8db
   **/
  createSuperdaoCrossChainProposal: GenericContractTxCall<
    ChainApi,
    (call: SuperdaoTraitsChainCallLike, options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {SuperdaoTraitsContractCallLike} call
   * @param {ContractTxOptions} options
   *
   * @selector 0x0071768f
   **/
  createContractCallProposal: GenericContractTxCall<
    ChainApi,
    (call: SuperdaoTraitsContractCallLike, options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {number} proposalId
   * @param {boolean} vote
   * @param {ContractTxOptions} options
   *
   * @selector 0x946595e4
   **/
  voteProposal: GenericContractTxCall<
    ChainApi,
    (proposalId: number, vote: boolean, options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
