// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result, AccountId32 } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
} from 'dedot/contracts';
import type {
  SuperdaoTraitsError,
  InkPrimitivesLangError,
  SuperdaoTraitsCallLike,
  SuperdaoTraitsVote,
  SuperdaoTraitsProposal,
} from './types';

export interface ContractQuery<ChainApi extends GenericSubstrateApi> extends GenericContractQuery<ChainApi> {
  /**
   *
   * @param {number} propId
   * @param {ContractCallOptions} options
   *
   * @selector 0x78e3d8b2
   **/
  resolveProposal: GenericContractQueryCall<
    ChainApi,
    (
      propId: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<boolean, SuperdaoTraitsError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x234726e7
   **/
  superDaoRegisterMember: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], SuperdaoTraitsError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xba5e25a8
   **/
  superDaoDeregisterMember: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {SuperdaoTraitsCallLike} call
   * @param {ContractCallOptions} options
   *
   * @selector 0x7c5f540f
   **/
  superDaoCreateProposal: GenericContractQueryCall<
    ChainApi,
    (
      call: SuperdaoTraitsCallLike,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<number, SuperdaoTraitsError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {number} propId
   * @param {SuperdaoTraitsVote} vote
   * @param {ContractCallOptions} options
   *
   * @selector 0x5002b426
   **/
  superDaoVote: GenericContractQueryCall<
    ChainApi,
    (
      propId: number,
      vote: SuperdaoTraitsVote,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], SuperdaoTraitsError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x51565355
   **/
  superDaoQueryGetMembers: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<AccountId32>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x77f94f7a
   **/
  superDaoQueryIsMember: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {number} index
   * @param {ContractCallOptions} options
   *
   * @selector 0x1421bc5e
   **/
  superDaoQueryGetProposal: GenericContractQueryCall<
    ChainApi,
    (
      index: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<SuperdaoTraitsProposal | undefined, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x8e77186a
   **/
  superDaoQueryGetProposals: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<[number, SuperdaoTraitsProposal]>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {number} proposalId
   * @param {ContractCallOptions} options
   *
   * @selector 0x19278efe
   **/
  superDaoQueryGetVotes: GenericContractQueryCall<
    ChainApi,
    (
      proposalId: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<[AccountId32, SuperdaoTraitsVote]>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x9b365037
   **/
  superDaoQueryGetVoteThreshold: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<number, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2c14957d
   **/
  superDaoQueryGetVotingPeriod: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<number, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x867a6620
   **/
  superDaoQueryGetActiveProposals: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<Array<number>, ContractCallResult<ChainApi>>>
  >;
}
